version: 2

sources:
  - name: raw
    schema: da_raw_data
    description: greenweez raw data source
    tables :
      - name: sales
        identifier: raw_da_sales
        description: sales of Greenweez / we have one row per productid found in each orders_id
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date as TIMESTAMP)"
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: amount paid
          - name: quantity
            description: quantity of products
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_da_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchase price
      - name: ship
        identifier: raw_da_ship
        description: ship of Greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: price paid for shipping
          - name: log_cost
            description: cost of preparing the parcel in the warehouse
          - name: ship_cost
            description: shipping cost paid by Greenweez to the carrier