version: 2

sources:
  - name: raw
    schema: da_raw_data
    tables :
      - name: sales
        identifier: raw_da_sales
      - name: product
        identifier: raw_da_product
      - name: ship
        identifier: raw_da_ship